### ISSUE TITLE
I got error while compiling klipper.

### ISSUE THREAD

**Issue by HongyongChoi7795** [0xD34D/klipper_ender3_v3_se#10]
While I compile klipper firmware for rp2040, I got this error.

![Error](https://github.com/0xD34D/klipper_ender3_v3_se/assets/106365428/d01d68b4-8f10-4d07-916d-e38b8a62707a)

My config was this.
![image](https://github.com/0xD34D/klipper_ender3_v3_se/assets/106365428/68d48756-35e2-484f-acf2-af1f4a4024ce)

**Comment by Alexandrinn** [comment]
# This file contains pin mappings for the stock 2022 Creality Ender 3
# V3 SE. To use this config, during "make menuconfig" select the
# STM32F103 with a "28KiB bootloader" and serial (on USART1 PA10/PA9)
# communication.
# "Enable extra low-leverl configuration options" and "Disable SWD on startup"
![Screenshot 2024-01-12 230411](https://github.com/0xD34D/klipper_ender3_v3_se/assets/33482807/84256044-81bf-47bd-8a63-001058991993)

**Comment by HongyongChoi7795** [comment]
> "# This file contains pin mappings for the stock 2022 Creality Ender 3 "# V3 SE. To use this config, during "make menuconfig" select the "# STM32F103 with a "28KiB bootloader" and serial (on USART1 PA10/PA9) "# communication. "# "Enable extra low-leverl configuration options" and "Disable SWD on startup" ![Screenshot 2024-01-12 230411](https://private-user-images.githubusercontent.com/33482807/296365250-84256044-81bf-47bd-8a63-001058991993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDI3MTIsIm5iZiI6MTcwNTEwMjQxMiwicGF0aCI6Ii8zMzQ4MjgwNy8yOTYzNjUyNTAtODQyNTYwNDQtODFiZi00N2JkLThhNjMtMDAxMDU4OTkxOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDIzMzMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMWVjYTFkMTVjY2ZjYmJiMDM1ZWIzMGYyMTMxNTIzY2IzNDJiYmZkODJiNWFmN2EyMmFkZWY3MWRhNzM1YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VweCa9OeNcJuOYiL_95gpPhn0vUe_pAwzgTZTnORCsA)

I tried to make firmware for my portable adxl345.

**Comment by schnoog** [comment]
As temporary fix to be able to compile the firmware for the RP2040 I added
 
#define CONFIG_CLOCK_FREQ 12000000

to src/hx711s.c and  src/dirzctl.c
would be great if that could be avoided.
