### ISSUE TITLE
Z_Adjust doesn't save when restarting printer

### ISSUE THREAD

**Issue by gadgethd** [0xD34D/klipper_ender3_v3_se#4]
**Describe the bug**
Z_Adjust doesnt apply when restarting printer as it is not a saved value by Klipper, it seems.

**To Reproduce**
1. Do a Z auto calibrate
2. Save Config and restart
3. see value gets removed after restart

Before restart:

<img width="444" alt="Screenshot 2023-11-18 at 2 06 20 am" src="https://github.com/0xD34D/klipper_ender3_v3_se/assets/111318106/cd78ad72-b9f3-4ac4-a737-f68799719c61">

After restart:

<img width="444" alt="Screenshot 2023-11-18 at 2 07 09 am" src="https://github.com/0xD34D/klipper_ender3_v3_se/assets/111318106/8804fa26-e744-4c7c-b2b9-17362ff46600">

**Expected behavior**
Whole Z offset to be saved on restart

**Additional context**

I believe this could be fixed by changing line 834 to include nozzle_z_offset in the calculation, then it would save as if it were a regular offset.

**Comment by pi3123** [comment]
The ZOffset is saved to the printer.cfg under [bltouch]
It doesn't save to the regular offset but it definetily saves it after running the SAVE_CONFIG

**Comment by gadgethd** [comment]
Yes the normal Z offset is saved, however the Z_Adjust doesnt get saved as its in the temp Z offset.

**Comment by gadgethd** [comment]
Ok so ive figured out why its doing this, its quite smart and I didn't notice. The temporary value is the difference between the previous Auto Z Offset and the new one, so you don't have to restart the printer. I think this is what you were mentioning before and I didn't fully understand it.
